# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 384d84cc6be02832a990d12f55144ea63d85a120b458f1f2b5d9e843e9ffbf1a13550df9bdc390302a468ff52fa3dc65485e8db263c98234b43cec4bcd41832d

test:
  secret_key_base: 28cc30c789c18279edd9ea5b46d0c25beed7a178dbfcf831d9980b7db5d6de3632f726b68f7f9cbc8348bfd5e681bde798643bc71159df1a72b25744b0e67db4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
